include:
  - project: "tulibraries/gitlab-ci-templates"
    file:
      - "lint_docker.yaml"
      - "build_docker.yaml"
      - "security_scan.yaml"
      - "kubectl_commands.yaml"

before_script:
  - source .env
  - export TAG="${DOCKER_IMAGE_VERSION}"
  - export VERSION="${DOCKER_IMAGE_VERSION}-${CI_COMMIT_SHORT_SHA}"

variables:
  IMAGE: "tulibraries/openssh-client"

stages:
  - lint
  - build
  - scan
  - tag

lint:
  extends: .lint_docker

build:
  stage: build
  extends: .build_image
  services:
    - name: harbor.k8s.temple.edu/gitlab-ci/docker:20-dind
      command: ["--tls=false"]

scan:
  stage: scan
  extends: .scanimage_high

tag_latest:
  stage: tag
  variables:
    TAG: latest
  extends: .tag_image_latest

tag:
  stage: tag
  extends: .tag_image
