include:
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file:
      - "lint_docker.yaml"
      - "build_and_scan_docker.yaml"
      - "kubectl_commands.yaml"
      - "sast_scanning.yaml"

before_script:
  - source .env
  - export TAG="${DOCKER_IMAGE_VERSION}"
  - export VERSION="${DOCKER_IMAGE_VERSION}-${CI_COMMIT_SHORT_SHA}"

variables:
  IMAGE: "tulibraries/openssh-client"

stages:
  - lint
  - build
  - tag

lint:
  extends: .lint_docker

build:
  stage: build
  extends: .build_image

tag_latest:
  stage: tag
  variables:
    TAG: latest
  extends: .tag_image

tag:
  stage: tag
  extends: .tag_image
